### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by hdf15804299051** [jwezorek/vs_pdfium#7]
if I want build a linux render pdf, what can i do?

**Comment by hdf15804299051** [comment]
I need write cmakelist ，and Which library files do I need to replace

**Comment by TechnicalGaur** [comment]
1-Create a CMakeLists.txt File
2- Determine Library Dependencies
  Here are some common ways to identify library dependencies:

Check Your Code: Look through your code for #include statements that reference external libraries. These statements can give you clues about which libraries your project uses.

Read Documentation: If you're using third-party libraries, consult their documentation or README files to understand their dependencies.

Check Package Manager Files: If you're using a package manager like CMake's FetchContent or Conan, check the configuration files (e.g., CMakeLists.txt or conanfile.txt) for library dependencies.

Examine Build Errors: If you encounter build errors related to missing libraries, the error messages may provide information about which libraries are needed.

Consult Project Documentation: If your project has documentation, it may list its library dependencies.

**Comment by hdf15804299051** [comment]
Hello, I am currently encountering a font related issue. My PDF file is still the same as the one I sent you last time, and its font is SimSun. However, when I parse it, the font of the parsed image becomes Lisu. It's very strange, but when I deleted the font file/usr/share/fonts/ttf/Lisu.ttf, the parsed image returned to normal and became a SimSun font. Therefore, I would like to inquire about the rules for matching fonts on your end

**Comment by hdf15804299051** [comment]
The operating system I am currently using is Linux, and my font directory uses/usr/share/fonts/ttf. There are only two files in this directory: Lisu.ttf and SimSun.ttf. If this directory does not contain any font files, Chinese garbled characters will appear when parsing PDFs. This is the situation in my current environment
